name: jeopardy_score_keeper
description: "Jeopard Score Keeper"
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: ^3.7.2
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  audioplayers: ^6.4.0
  intl: ^0.20.2
  sqlite3: ^2.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
